COPY /B "load_1.dds" "load_2.dds"
COPY /B "load_1.dds" "load_3.dds"
COPY /B "load_1.dds" "load_4.dds"
COPY /B "load_1.dds" "load_5.dds"
COPY /B "load_1.dds" "load_6.dds"
COPY /B "load_1.dds" "load_7.dds"
COPY /B "load_1.dds" "load_8.dds"
COPY /B "load_1.dds" "load_9.dds"
COPY /B "load_1.dds" "load_10.dds"
COPY /B "load_1.dds" "load_11.dds"
COPY /B "load_1.dds" "load_12.dds"
COPY /B "load_1.dds" "load_13.dds"
COPY /B "load_1.dds" "load_14.dds"
COPY /B "load_1.dds" "load_15.dds"
COPY /B "load_1.dds" "load_16.dds"
COPY /B "load_1.dds" "load_17.dds"
pause